name: CreateZip
on:
  workflow_call:
    inputs:
      tag:
        type: string
        required: false
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: false

jobs:
    Create-Zip:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
          with:
            fetch-tags: true
            ref: ${{ inputs.tag }}

        - uses: actions/setup-dotnet@v4

        - name: create zip
          env:
            TAG: ${{ inputs.tag }}
          run: |
            cd .github/CreateZip
            dotnet run

            cd ../../
            mv reina-s-liltoon-ndmf-utility.zip reina-s-liltoon-ndmf-utility-$TAG.zip


        - uses: actions/upload-artifact@v4
          with:
            name: reina-s-liltoon-ndmf-utility
            path: reina-s-liltoon-ndmf-utility-${{ inputs.tag }}.zip
